# Generated by Django 3.1 on 2021-05-18 10:22

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('slug', models.CharField(blank=True, max_length=200, unique=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('logo', models.ImageField(default='logos/default.jpeg', upload_to='logos/')),
                ('type', models.CharField(choices=[('FL', 'Flight'), ('TR', 'Train'), ('BU', 'Bus')], max_length=2)),
            ],
            options={
                'verbose_name': 'Agency',
                'verbose_name_plural': 'Agencies',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('capacity', models.PositiveIntegerField(verbose_name='Capacity')),
                ('starts', models.DateTimeField(verbose_name='Starts at')),
                ('arrives', models.DateTimeField(verbose_name='Arrives at')),
                ('train_type', models.CharField(max_length=20, verbose_name='Train Type')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_tickets', to='ticket.agency')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_destinations', to='ticket.city', verbose_name='Destination')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='train_origins', to='ticket.city', verbose_name='Origin')),
            ],
            options={
                'verbose_name': 'Train',
                'verbose_name_plural': 'Trains',
            },
        ),
        migrations.CreateModel(
            name='MiddleWayStaion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.city', verbose_name='City')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='middle_ways', to='ticket.train', verbose_name='')),
            ],
            options={
                'verbose_name': 'MiddleWayStaion',
                'verbose_name_plural': 'MiddleWayStaions',
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('capacity', models.PositiveIntegerField(verbose_name='Capacity')),
                ('starts', models.DateTimeField(verbose_name='Starts at')),
                ('arrives', models.DateTimeField(verbose_name='Arrives at')),
                ('flight_class', models.CharField(choices=[('EC', 'Economy'), ('BS', 'Business')], max_length=2)),
                ('plane_model', models.CharField(max_length=20, verbose_name='Plane Model')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_tickets', to='ticket.agency')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_destinations', to='ticket.city', verbose_name='Destination')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_origins', to='ticket.city', verbose_name='Origin')),
            ],
            options={
                'verbose_name': 'Flight',
                'verbose_name_plural': 'Flights',
            },
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('capacity', models.PositiveIntegerField(verbose_name='Capacity')),
                ('starts', models.DateTimeField(verbose_name='Starts at')),
                ('arrives', models.DateTimeField(verbose_name='Arrives at')),
                ('bus_type', models.CharField(choices=[('VIP', 'VIP'), ('CLS', 'Classic')], max_length=3)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_tickets', to='ticket.agency')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_destinations', to='ticket.city', verbose_name='Destination')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bus_origins', to='ticket.city', verbose_name='Origin')),
            ],
            options={
                'verbose_name': 'Bus',
                'verbose_name_plural': 'Buses',
            },
        ),
    ]
