# Generated by Django 3.1 on 2021-05-18 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiddleWayStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(verbose_name='Time')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.city', verbose_name='City')),
            ],
            options={
                'verbose_name': 'MiddleWayStaion',
                'verbose_name_plural': 'MiddleWayStaions',
            },
        ),
        migrations.DeleteModel(
            name='MiddleWayStaion',
        ),
        migrations.AddField(
            model_name='train',
            name='middle_ways',
            field=models.ManyToManyField(to='ticket.MiddleWayStation', verbose_name='trains'),
        ),
    ]
