# Generated by Django 3.1 on 2021-05-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_auto_20210504_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='slug',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='arrives',
            field=models.DateTimeField(verbose_name='Arrives at'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='starts',
            field=models.DateTimeField(verbose_name='Starts at'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrives',
            field=models.DateTimeField(verbose_name='Arrives at'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='starts',
            field=models.DateTimeField(verbose_name='Starts at'),
        ),
    ]
